Gemfile
Gemfile.lock
app/controllers/core_data_connector/media_contents_controller.rb
app/controllers/core_data_connector/relationships_controller.rb
app/models/concerns/core_data_connector/ownable.rb
app/models/concerns/core_data_connector/relateable.rb
app/models/core_data_connector/media_content.rb
app/models/core_data_connector/organization.rb
app/models/core_data_connector/person.rb
app/models/core_data_connector/place.rb
app/models/core_data_connector/project_model.rb
app/models/core_data_connector/relationship.rb
app/policies/core_data_connector/media_content_policy.rb
app/policies/core_data_connector/relationship_policy.rb
app/serializers/core_data_connector/media_contents_serializer.rb
config/routes.rb
core_data_connector.gemspec
db/migrate/20230926143625_create_core_data_connector_media_contents.rb
db/migrate/20231018165824_add_user_defined_fields_to_core_data_connector_media_contents.rb
lib/core_data_connector/engine.rb
lib/generators/core_data_connector/install/install_generator.rb

This pull request adds the `media_contents` table, models, policy, serializer, and API endpoint. It also integrates the `triple-eye-effable` gem. It also adds some improvements for searching and sorted related records (see `relationships_controller`). See [this](https://github.com/performant-software/core-data-cloud/pull/28) pull request in the core-data-cloud repo for screenshots.

CDC #18 - Media

---

app/controllers/concerns/core_data_connector/ownable_controller.rb
app/controllers/core_data_connector/project_models_controller.rb
app/controllers/core_data_connector/relationships_controller.rb
app/models/core_data_connector/project_model.rb
app/models/core_data_connector/project_model_relationship.rb
app/models/core_data_connector/relationship.rb
app/policies/core_data_connector/project_model_policy.rb
app/serializers/core_data_connector/project_models_serializer.rb
app/serializers/core_data_connector/relationships_serializer.rb
db/migrate/20231022110706_add_inverse_fields_to_project_model_relationships.rb

This pull request adds the `inverse_project_model_relationships` relationship to `project_models`. It also updates the `relationships_controller` to handle the `inverse` parameter.

CDC #23 - Inverse relationships

---

app/controllers/concerns/core_data_connector/ownable_controller.rb
app/controllers/core_data_connector/project_model_accesses_controller.rb
app/controllers/core_data_connector/project_models_controller.rb
app/controllers/core_data_connector/projects_controller.rb
app/models/concerns/core_data_connector/ownable.rb
app/models/core_data_connector/project_model.rb
app/models/core_data_connector/project_model_access.rb
app/models/core_data_connector/project_model_share.rb
app/policies/concerns/core_data_connector/ownable_policy.rb
app/policies/concerns/core_data_connector/ownable_scope.rb
app/policies/core_data_connector/media_content_policy.rb
app/policies/core_data_connector/organization_policy.rb
app/policies/core_data_connector/person_policy.rb
app/policies/core_data_connector/place_policy.rb
app/policies/core_data_connector/project_model_access_policy.rb
app/policies/core_data_connector/project_model_policy.rb
app/policies/core_data_connector/project_policy.rb
app/policies/core_data_connector/relationship_policy.rb
app/serializers/concerns/core_data_connector/ownable_serializer.rb
app/serializers/core_data_connector/media_contents_serializer.rb
app/serializers/core_data_connector/organizations_serializer.rb
app/serializers/core_data_connector/people_serializer.rb
app/serializers/core_data_connector/places_serializer.rb
app/serializers/core_data_connector/project_model_accesses_serializer.rb
app/serializers/core_data_connector/project_models_serializer.rb
app/serializers/core_data_connector/projects_serializer.rb
config/routes.rb
db/migrate/20231030105236_add_discoverable_to_projects.rb
db/migrate/20231030105439_create_core_data_connector_project_model_accesses.rb
db/migrate/20231030182359_create_core_data_connector_project_model_shares.rb

This pull request adds the `project_model_accesses` and `project_model_shares` tables/models to support data sharing.

CDC #4 - Share data

---

Gemfile.lock
app/controllers/core_data_connector/places_controller.rb
app/models/core_data_connector/place.rb
app/models/core_data_connector/place_geometry.rb
app/policies/core_data_connector/place_policy.rb
app/serializers/core_data_connector/place_geometries_serializer.rb
app/serializers/core_data_connector/places_serializer.rb
app/services/core_data_connector/geometry.rb
core_data_connector.gemspec
db/migrate/20231106203938_enable_postgis_extension.rb
db/migrate/20231106204031_create_core_data_connector_place_geometries.rb

This pull requests enables the `postgis` extension for Postgres and adds the `place_geometries` model. Currently, a `place` can have a single `place_geometry`.

CDC #35 - Place geometry

---

app/controllers/concerns/core_data_connector/importable_controller.rb
app/controllers/core_data_connector/places_controller.rb
app/services/core_data_connector/import/base.rb
app/services/core_data_connector/import/places.rb
config/routes.rb
db/migrate/20231110152017_add_z_place_id_to_core_data_connector_places.rb

This pull request implements the `ImportableController` and the CSV import architecture. A concrete implementation is included for the `places` model.

CDC #38 - Data import

---

Gemfile
Gemfile.lock

This pull request updates the `resource_api` gem to the latest version.

CDC #72 - Relationships API

---

Gemfile
Gemfile.lock
app/controllers/concerns/core_data_connector/public/relateable_controller.rb
app/serializers/core_data_connector/public/linked_open_data_serializer.rb
app/serializers/core_data_connector/public/media_contents_serializer.rb
app/serializers/core_data_connector/public/organizations_serializer.rb
app/serializers/core_data_connector/public/people_serializer.rb
app/serializers/core_data_connector/public/places_serializer.rb
app/serializers/core_data_connector/public/taxonomies_serializer.rb
config/locales/en.yml

This pull request updates the `linked_open_data_serializer` to use the `AnnotationPage` syntax to build the JSON response.
**Note:** This pull request is dependent on a [PR](https://github.com/performant-software/resource-api/pull/40) in the `resource-api` repo.

CDC #79 - Annotation Page

---

README.md

Adding release documentation to README.md.

CDC #31 - Release Documentation

---

app/serializers/core_data_connector/public/places_serializer.rb

This pull request adds the `geometry` attribute to the `places_serializer` for the `/public/places/:id/places` route.

CDC #88 - Related Places Geometry

---

app/controllers/core_data_connector/projects_controller.rb
app/models/core_data_connector/project_model.rb
app/policies/core_data_connector/project_policy.rb
config/routes.rb

This pull request adds the `/projects/:id/clear` API endpoint to allow all data entered in a project to be removed. This action can only be performed by admin users.

CDC #95 - Clear data

---

app/controllers/core_data_connector/public/projects_controller.rb
config/routes.rb

This pull request implements the `/public/projects/:id/descriptors` API endpoint for loading all of the custom labels for a Core Data project.
Using "Bischoff Staging" project
```
{
"descriptors": [
{
"identifier": "ac77327b-cf4e-46e8-aa2d-864ed2763874",
"label": "Manuscripts"
},
{
"identifier": "e943f155-eac8-4c00-92c5-e770ece85282",
"label": "Catalog Number",
"context": "Manuscripts"
},
{
"identifier": "6678ddbb-6347-4f75-8689-6c4cfeb8990c",
"label": "Text",
"context": "Manuscripts"
},
{
"identifier": "93abc165-5cb5-42b3-9337-ca9c2e2f9f76",
"label": "Original Date",
"context": "Manuscripts"
},
{
"identifier": "0a5c1301-3776-41ee-b30b-c4a8d11a242a",
"label": "Provenance Date",
"context": "Manuscripts"
},
{
"identifier": "886841ba-779e-4ed4-94b9-fe03d43975b0",
"label": "Measures", …
```

CDC #144 - Project descriptors

---

app/controllers/core_data_connector/public/public_controller.rb

This pull request updates the public API for related records to include an optional `project_model_relationship_uuid` parameter to only include the related records for a specific relationship:
`/public/places/:uuid/people?project_model_relationship_uuid=:uuid`
`/public/places/32c3b42a-c118-48c6-9ee4-65017e9294e9/people?project_model_relationship_uuid=66966f96-51f7-4ce7-96df-2360ca85b183`

CDC #147 - Public related records API

---

app/serializers/concerns/core_data_connector/public/v0/linked_places/typeable_serializer.rb

This pull request fixes an `include` issue in the typeable_serializer.

CDC #195 - People API

---

Gemfile
Gemfile.lock
app/controllers/core_data_connector/media_contents_controller.rb

This pull request updates the `triple_eye_effable` gem to the latest version.

IIIF #54 - Redirects

---

Gemfile
Gemfile.lock

This pull request updates the `user_defined_fields` gem to the latest version.

CDC #157 - List Columns

---

app/services/core_data_connector/export/relationship.rb

This pull request fixes the order of the fields in the `relationships.csv` export.

CDC #235 - Relationships.csv field order

---

Gemfile
Gemfile.lock
app/controllers/concerns/core_data_connector/manifests_controller.rb

This pull request updates the `resource_api` and `user_defined_fields` gems to the latest versions to support the image upload changes.
It also fixes an issue that occurred when an error occurred uploading multiple images.

CDC #237 - Image Uploads

---

app/services/core_data_connector/search/base.rb

This pull request adds the `owner_project` and `all_projects` attributes to the search document JSON.

CDC #80 - Project facet

---

Gemfile
Gemfile.lock

This pull request updates the `resource_api` gem to the latest version.

CDC #301 - Related Record Pagination

---

app/services/core_data_connector/import_analyze/import.rb

This pull request fixes two separate issues:
- There was an issue with the way the query was being built in the `find_merges_by_uuid` method. The subquery was being appended to the query, but the new resulting object was not being assigned.
- There was an issue that would result in that would look like duplicate records being imported, if multiple records contained in the import were merged into the same record.

CDC #353 - Import duplicates

---

app/services/core_data_connector/import/base.rb

Per performant-software/core-data-cloud#403:
- In import, limit `jsonb_build_object` function calls to 100 arguments at a time, then concatenate results using `||`
Tested locally and works on project with 52 UDFs on a single model.

Batch UDF json function call by 100 in import (CDC #403)

---

app/services/core_data_connector/iiif/manifest.rb

This pull request adds the `name` and `id` sorting to IIIF manifest generation, in addition to the manual `order`.

CDC #431 - Manifest sorting
