performant-software/core-data-connector

Gemfile, Gemfile.lock, app/controllers/core_data_connector/organizations_controller.rb, app/controllers/core_data_connector/people_controller.rb, app/controllers/core_data_connector/places_controller.rb, app/controllers/core_data_connector/relationships_controller.rb, app/models/core_data_connector/organization.rb, app/models/core_data_connector/person.rb, app/models/core_data_connector/place.rb, app/models/core_data_connector/project_model.rb, app/models/core_data_connector/project_model_relationship.rb, app/models/core_data_connector/relationship.rb, app/policies/core_data_connector/organization_policy.rb, app/policies/core_data_connector/person_policy.rb, app/policies/core_data_connector/place_policy.rb, app/policies/core_data_connector/project_model_policy.rb, app/policies/core_data_connector/relationship_policy.rb, app/serializers/core_data_connector/organizations_serializer.rb, app/serializers/core_data_connector/people_serializer.rb, app/serializers/core_data_connector/places_serializer.rb, app/serializers/core_data_connector/project_models_serializer.rb, app/serializers/core_data_connector/relationships_serializer.rb, db/migrate/20230918201537_add_user_defined_fields_to_core_data_connector_organizations.rb, db/migrate/20230918201546_add_user_defined_fields_to_core_data_connector_people.rb, db/migrate/20230918201552_add_user_defined_fields_to_core_data_connector_places.rb, db/migrate/20230918201557_add_user_defined_fields_to_core_data_connector_relationships.rb
This pull request installs the `user_defined_fields` gem into the Core Data Connector. Fields can be defined for `project_models` and `project_model_relationships` records. Data will be stored on `organizations`, `people`, `places`, and `relationships`.
**Note:** Before merging, this pull request has dependent PRs in the resource-api and user-defined-fields repositories.
=> CDC #16 - User defined fields

app/services/core_data_connector/import/base.rb
This pull request removes a hard-coded `project_model_id` value from the base importer.
=> CDC #38 - Data Import

lib/typesense/helper.rb
This pull request adds the `coordinates` fields to the Typesense schema to support Geosearch.
=> CDC #74 - Geosearch

Gemfile.lock, core_data_connector.gemspec, lib/core_data_connector/engine.rb
This pull request adds the `rack-cors` dependency and an initializer to enable CORS for the `/core_data/public` API endpoints.
=> CDC #78 - Adding rack-cors dependency; Adding initializer for CORS

Gemfile, Gemfile.lock, app/controllers/concerns/core_data_connector/public/relateable_controller.rb, app/controllers/concerns/core_data_connector/public/unauthenticateable_controller.rb, app/services/core_data_connector/search/base.rb
This pull request updates the `unauthenticateable` concern to override the `find_record` method to lookup records in the database by `uuid` instead of database ID. This includes updating the `resource_api` gem to the latest version.
It also refactors the `relateable_controller` concern to avoid multiple queries for the same record for nested resources (i.e. `/places/:uuid/people`.
=> CDC #87 - Resource IDs

app/services/core_data_connector/import/importer.rb, app/services/core_data_connector/import/instances.rb, app/services/core_data_connector/import/items.rb, app/services/core_data_connector/import/relationships.rb, app/services/core_data_connector/import/works.rb, db/migrate/20240108143923_add_z_instance_id_to_core_data_connector_instances.rb, db/migrate/20240108143938_add_z_item_id_to_core_data_connector_items.rb, db/migrate/20240108143947_add_z_work_id_to_core_data_connector_works.rb, db/migrate/20240108194908_add_z_source_fields_to_names.rb
- adds modules to the `Import` service for Instances, Items, and Works
- adds migrations for temporary `z_` columns on the source models and the names model to facilitate the import process
=> Source imports

app/serializers/core_data_connector/instances_serializer.rb, app/serializers/core_data_connector/items_serializer.rb, app/serializers/core_data_connector/works_serializer.rb
This is a small PR to fix an issue that was preventing sources from displaying user-defined fields. The solution is to add `include UserDefinedFields::FieldableSerializer` to all three serializers.
=> Add `FieldableSerializer` to source models

app/services/core_data_connector/import/base.rb, app/services/core_data_connector/import/importer.rb, app/services/core_data_connector/import/relationships.rb, app/services/core_data_connector/import/taxonomies.rb, db/migrate/20240117215342_add_z_taxonomy_id_to_taxonomies.rb
- adds a `Taxonomies` class to the import service
- adds a migration for the `z_taxonomy_id` column in the taxonomies table
- fixes an issue in the `Import::Base` class where the `transform` assumed that a model has a `user_defined` column and would attempt to `SET` it even if it doesn't exist
=> Add taxonomy imports

app/services/core_data_connector/authority/http.rb, app/services/core_data_connector/authority/wikidata.rb
Fixing a bug with `typhoeus` require in the wrong class. Moving `typhoeus` require into http.rb concern.
=> CDC #54 - External Identifiers

app/models/core_data_connector/web_authority.rb, app/services/core_data_connector/authority/dpla.rb
- adds a `Dpla` class to the `Authority` module to enable DPLA for external identifiers
(this one was a lot more straightforward than BnF)
=> Add Digital Public Library of America as an authority

app/models/core_data_connector/web_authority.rb, app/services/core_data_connector/authority/jisc.rb
- adds a `Jisc` class to the `Authority` module to enable linking Core Data records with external Jisc records
=> Add Jisc as an authority

app/models/core_data_connector/web_authority.rb, app/services/core_data_connector/authority/viaf.rb
- adds a Viaf class to the Authority module to enable linking Core Data records with external Viaf records
=> Add Viaf as an authority

Gemfile, Gemfile.lock, app/models/core_data_connector/web_authority.rb, app/services/core_data_connector/authority/atom.rb, app/services/core_data_connector/authority/bnf.rb, app/services/core_data_connector/authority/dpla.rb, app/services/core_data_connector/authority/http.rb, app/services/core_data_connector/authority/jisc.rb, app/services/core_data_connector/authority/viaf.rb, app/services/core_data_connector/authority/wikidata.rb, core_data_connector.gemspec
- adds an `Authority` module for BnF
- adds the `rexml` gem, which was required for converting the XML from their response to JSON
- fixes an issue with the scope of the `BASE_URL` constant in the Wikidata authority class where it overwrote the value of BnF's `BASE_URL` in an unpredictable manner
- also fixes where I made the same mistake in the Jisc and VIAF classes
- refactors the `Authority::Http` class to `yield` the response so we can handle it in different ways depending on the API
=> Add Bibliothèque nationale de France as a web authority

app/services/core_data_connector/search/base.rb
https://github.com/performant-software/core-data-cloud/issues/135 was caused by some missed boilerplate in the `Search` module, specifically in the `build_relationships` method. I've added the three source types to that method and indexed some test data to confirm the fix.
=> Fix sources missing in `build_relationships`

app/serializers/core_data_connector/public/user_defined_serializer.rb, app/services/core_data_connector/search/base.rb
This small PR fixes two issues where Core Data tried to access a user-defined field by its UUID without first checking if the `user_defined` field was actually a JSON object. An empty user-defined field can be either `{}` (an empty object) or `nil`, so I've fixed the issue by checking that `user_defined` isn't `nil` before proceeding to try to look up a value in it.
=> Fix errors related to `nil``user_defined` value

Gemfile, Gemfile.lock, README.md, app/controllers/concerns/core_data_connector/manifests_controller.rb, app/controllers/concerns/core_data_connector/public/nestable_controller.rb, app/controllers/core_data_connector/public/manifests_controller.rb, app/controllers/core_data_connector/public/public_controller.rb, app/controllers/core_data_connector/relationships_controller.rb, app/models/concerns/core_data_connector/manifestable.rb, app/models/core_data_connector/instance.rb, app/models/core_data_connector/item.rb, app/models/core_data_connector/location.rb, app/models/core_data_connector/manifest.rb, app/models/core_data_connector/place.rb, app/models/core_data_connector/project_model_relationship.rb, app/models/core_data_connector/work.rb, app/serializers/core_data_connector/project_models_serializer.rb, app/services/core_data_connector/iiif/manifest.rb, config/locales/en.yml, config/routes.rb, db/migrate/20240206191858_add_uuid_to_project_models.rb, db/migrate/20240206191905_add_uuid_to_project_model_relationships.rb, db/migrate/20240212175452_create_core_data_connector_manifests.rb, lib/core_data_connector/engine.rb, lib/tasks/core_data_connector_tasks.rake
This pull request adds the `manifests` table and models. It also creates the `/services/iiif/manifest` service used to create IIIF manifests for records that are related to "Media Content" records. It also adds the `uuid` column to `project_models` and `project_model_relationships`.
IIIF manifests will be re-generated automatically each time a related `media_contents` record is create or deleted.
See screenshots in [core-data-cloud](https://github.com/performant-software/core-data-cloud/pull/146) PR.
=> CDC #114 - IIIF Manifests

README.md, app/services/core_data_connector/search/base.rb, app/services/core_data_connector/search/instance.rb, app/services/core_data_connector/search/item.rb, app/services/core_data_connector/search/organization.rb, app/services/core_data_connector/search/person.rb, app/services/core_data_connector/search/place.rb, app/services/core_data_connector/search/taxonomy.rb, app/services/core_data_connector/search/work.rb, lib/tasks/typesense.rake, lib/typesense/helper.rb
This pull request refactors the way we're bundling related/nested objects into the Typesense search index. Previously, we were putting everything into a `related_<type>` (e.g `related_people`). This posed a problem for projects that had multiple types of related people wished to retrieve search results for a particular relationship.
Instead of using the `related_<type>` as the nested object key, we'll use the `uuid` of the `project_model_relationship` record. This can be used in concert with the [project descriptors](https://github.com/performant-software/core-data-connector/pull/68) feature to retrieve the appropriate labels.
Additionally, this pull request adds the `typesense:update` rake task. The purpose of this task is to get around an issue with Typesense's auto-detection schema and …
=> CDC #142 - Search relationships

app/controllers/core_data_connector/public/manifests_controller.rb, app/services/core_data_connector/iiif/manifest.rb, db/migrate/20240305174127_add_item_count_to_manifests.rb
This pull request adds the `item_count` column to `core_data_connector_manifests`. It also updates the `/public/<model>/:uuid/manifests` API endpoint to send the `item_count` to IIIF Cloud when generating the collection manifest.
=> CDC #161 - IIIF Thumbnails

app/controllers/core_data_connector/public/projects_controller.rb
This pull request adds the `context` attribute to project model relationships in the `/public/projects/:id/descriptors` endpoint. This value will be the name of the primary model to which the relationship belongs.
=> CDC #160 - Project Descriptors

app/controllers/core_data_connector/projects_controller.rb, app/policies/core_data_connector/project_policy.rb, app/serializers/core_data_connector/project_variables_serializer.rb, config/routes.rb
This pull request adds the `/projects/:id/export_variables` API endpoint, which allows a project's model, relationship, and field `id` and `uuid` values to be exported as environment variables. See screenshots in [core-data-cloud ](https://github.com/performant-software/core-data-cloud/pull/170)PR.
=> CDC #169 - Export Variables

app/controllers/core_data_connector/project_models_controller.rb, app/models/core_data_connector/instance.rb, app/models/core_data_connector/item.rb, app/models/core_data_connector/work.rb
This pull request fixes a bug with the validation of user defined fields on `instances`, `items`, and `works` records. This issue crept in [here](https://github.com/performant-software/user-defined-fields/blob/master/app/models/concerns/user_defined_fields/fieldable.rb#L30), when attempting to validate that all required fields were entered. Since the models did not implement the `resolve_defineable` method, the concern was assuming that the user defined fields were defined at the system level, which is not the case for Core Data. The result was that if Project A marked a `works` user-defined field as required, that field was also being required in the `works` records for Project B.
Additionally, this pull request orders the model class dropdown alphabetically.
=> CDC #179 - Works

app/controllers/core_data_connector/public/instances_controller.rb, app/controllers/core_data_connector/public/items_controller.rb, app/controllers/core_data_connector/public/linked_places/places_controller.rb, app/controllers/core_data_connector/public/works_controller.rb, app/controllers/core_data_connector/web_authorities_controller.rb, app/models/core_data_connector/web_identifier.rb, app/serializers/core_data_connector/public/instances_serializer.rb, app/serializers/core_data_connector/public/items_serializer.rb, app/serializers/core_data_connector/public/linked_places/places_serializer.rb, app/serializers/core_data_connector/public/web_identifiers_serializer.rb, app/serializers/core_data_connector/public/works_serializer.rb, app/services/core_data_connector/authority/atom.rb, app/services/core_data_connector/authority/base.rb, app/services/core_data_connector/authority/bnf.rb, app/services/core_data_connector/authority/dpla.rb, app/services/core_data_connector/authority/jisc.rb, app/services/core_data_connector/authority/viaf.rb, app/services/core_data_connector/authority/wikidata.rb, lib/tasks/core_data_connector_tasks.rake
This pull request adds the `web_identifiers` attribute to the public API for `instances`, `items`, `places`, and `works` API endpoints.
This pull request also adds the `find_identifier` callback to `web_identifier.rb`, which will allow for specific web authority implementations to do some pre-processing before the record is created. In the case of AtoM, we're making calls to the API to retrieve the name of the parent records in the Fond > Services > File hierarchy.
All web authority implementations will now extend the `Base` class in order to ensure the `before_create` method exists on the service.
=> CDC #173 - AtoM identifiers

app/policies/core_data_connector/project_model_policy.rb
This pull request fixes a bug that was occurring when a user had the role of "Editor" in a project. Attempting to access the `/project_models` API endpoint would return a 403 because it was set up to only list the records for a project "Owner". The solution was to update the API endpoint to return the expected records for all members of the project (regardless of role).
=> CDC #189 - Authorization

Gemfile, Gemfile.lock, app/controllers/concerns/core_data_connector/public/nestable_controller.rb, app/controllers/core_data_connector/events_controller.rb, app/controllers/core_data_connector/public/events_controller.rb, app/controllers/core_data_connector/public/linked_places/events_controller.rb, app/controllers/core_data_connector/relationships_controller.rb, app/models/core_data_connector/event.rb, app/models/core_data_connector/relationship.rb, app/policies/core_data_connector/event_policy.rb, app/serializers/core_data_connector/events_serializer.rb, app/serializers/core_data_connector/public/events_serializer.rb, app/serializers/core_data_connector/public/linked_places/events_serializer.rb, app/services/core_data_connector/import/events.rb, app/services/core_data_connector/import/importer.rb, app/services/core_data_connector/import/relationships.rb, app/services/core_data_connector/search/base.rb, app/services/core_data_connector/search/event.rb, config/routes.rb, core_data_connector.gemspec, db/migrate/20240416153109_create_core_data_connector_events.rb, db/migrate/20240416175657_add_user_defined_fields_to_core_data_connector_events.rb, lib/generators/core_data_connector/install/install_generator.rb
This pull request implements the `events` model in Core Data:
- Creates the `/core_data/events` API endpoints used by admin CMS
- Creates the `/core_data/public/events` API endpoints used by consumers
- Updates the search service to support events
- Updates the import service to support events
See screenshots on `core-data-cloud` [PR](https://github.com/performant-software/core-data-cloud/pull/191).
=> CDC #27 - Events

README.md, app/services/core_data_connector/search/base.rb, app/services/core_data_connector/search/item.rb, lib/typesense/helper.rb
This pull request makes the following changes to the Typesense indexing process:
- Updates each document to use the `uuid` value as the Typesense document ID. This will allowing updating records from FairCopy.cloud by `uuid`.
- Updates the document index process to use the `emplace` action, rather than `upsert`. This action does not require the full document to be sent, which supports only updating a partial set of attributes. This will allow the bulk of the attributes to be set by Core Data, and the document text to be set by FairCopy.cloud, without them overwriting each other. This also allows the indexing process to be run multiple times in Core Data without overwriting updates from FairCopy.cloud.
- Updates the document index process to remove any documents from the index that are not …
=> CDC #198 - Items Search

app/controllers/core_data_connector/public/v1/public_controller.rb, config/routes/public/v0.rb, config/routes/public/v1.rb
This pull request adds back the index endpoints to the `v0` and `v1` versions of the API (e.g. `/public/places?project_ids=1`).
=> CDC #210 - Index Endpoints

app/controllers/core_data_connector/public/v1/projects_controller.rb, app/serializers/concerns/core_data_connector/public/v1/typeable_serializer.rb, app/services/core_data_connector/search/base.rb
This pull request makes the following changes:
- Adds the `inverse_label` attribute to the `/public/projects/:id/descriptors` API endpoint
- Adds the `project_model_relationship_uuid` and `project_model_relationship_inverse` attributes to the `/public/*/:uuid/*` API endpoints
- Adds the `inverse` attribute to the nested related records in search
=> CDC #214 - Relationship Descriptors

app/controllers/concerns/core_data_connector/mergeable_controller.rb, app/controllers/core_data_connector/events_controller.rb, app/controllers/core_data_connector/instances_controller.rb, app/controllers/core_data_connector/items_controller.rb, app/controllers/core_data_connector/media_contents_controller.rb, app/controllers/core_data_connector/organizations_controller.rb, app/controllers/core_data_connector/people_controller.rb, app/controllers/core_data_connector/places_controller.rb, app/controllers/core_data_connector/taxonomies_controller.rb, app/controllers/core_data_connector/works_controller.rb, app/models/core_data_connector/event.rb, app/models/core_data_connector/media_content.rb, app/models/core_data_connector/organization.rb, app/models/core_data_connector/person.rb, app/models/core_data_connector/taxonomy.rb, app/policies/concerns/core_data_connector/mergeable_policy.rb, app/policies/core_data_connector/event_policy.rb, app/policies/core_data_connector/instance_policy.rb, app/policies/core_data_connector/item_policy.rb, app/policies/core_data_connector/media_content_policy.rb, app/policies/core_data_connector/organization_policy.rb, app/policies/core_data_connector/person_policy.rb, app/policies/core_data_connector/place_policy.rb, app/policies/core_data_connector/taxonomy_policy.rb, app/policies/core_data_connector/work_policy.rb, app/services/core_data_connector/merge/merger.rb, config/locales/en.yml, config/routes/admin.rb
This pull request adds the `/core_data/*/merge` API endpoints for merging together multiple records. The endpoints will accept a payload and an array of ID values. The payload will be used to create a new record. Relationships, manifests, and web identifiers connected to the merged records will be copied over to the newly created created. The merged records will then be removed.
There is a special edge case in the `media_contents_controller` for merging records. The front-end doesn't actually have access to the binary content of the media, so we can't simply `POST` the entire new record like we would if the user was uploading a file. Instead, we'll pass the `content_url` to the server. The controller will then fetch file content, write it to a file, and instantiate a new …
=> CDC #205 - Merge Records

app/controllers/concerns/core_data_connector/ownable_controller.rb
This pull request adds the `search_uuid` method to the `ownable_controller` to allow searching for records by the `uuid` value. Unlike most searches, this will require an exact match, rather than a partial match.
=> CDC #232 - Adding search_uuid method to ownable_controller

app/controllers/core_data_connector/projects_controller.rb, app/models/core_data_connector/relationship.rb, app/models/core_data_connector/web_identifier.rb, app/policies/core_data_connector/project_policy.rb, app/serializers/core_data_connector/project_configurations_serializer.rb, app/services/core_data_connector/export/exporter.rb, app/services/core_data_connector/file_system.rb, app/services/core_data_connector/queries.rb, config/routes/admin.rb
This pull request adds the `/projects/:id/export_data` API endpoint, which will return a `zip` files containing CSVs for the data contained in the specified project. This will include all records added by the specified project, and all records shared with the specified project. This feature was design in order to:
1. Serve as a helper for moving data from one Core Data instance to another
2. Serve as a mechanism for providing customers with their data
There are a few assumptions made as part of this implementation:
- Data will only ever be exported by admin users.
- The `uuid` values of all records will remain intact. The assumption here is that we're moving data from Instance A to Instance B of Core Data. Instance B will become the new source of truth and Instance A will be deprecated.
- …
=> CDC #178 - CSV Export

app/controllers/core_data_connector/project_models_controller.rb, app/policies/core_data_connector/project_model_policy.rb, app/serializers/core_data_connector/project_models_serializer.rb, db/migrate/20240717155011_add_order_to_project_models.rb, db/migrate/20240717155610_add_order_to_project_model_relationships.rb
This pull request adds the ability to add an `order` attribute to `project_models` and `project_models_relationships` records. See screenshots in the `core-data-cloud` [PR](https://github.com/performant-software/core-data-cloud/pull/245).
=> CDC #31 - Model Menu

app/models/core_data_connector/place_layer.rb, app/policies/core_data_connector/place_policy.rb, app/serializers/core_data_connector/place_layers_serializer.rb, app/serializers/core_data_connector/public/v0/linked_places/place_layers_serializer.rb, app/serializers/core_data_connector/public/v1/place_layers_serializer.rb, db/migrate/20240722113555_rename_place_layers_geometry_to_content.rb
This pull request renames the `geometry` column on `core_data_connector_place_layers` to `content` to support Geo-referenced images (IIIF manifest) content. We still include the `geometry` attribute in both `v0` and `v1` of the public API to maintain backwards compatibility.
See screenshots on `core-data-cloud` [PR](https://github.com/performant-software/core-data-cloud/pull/250).
=> CDC #248 - Geo-reference layers

app/controllers/core_data_connector/public/v1/events_controller.rb, app/controllers/core_data_connector/public/v1/manifests_controller.rb, app/services/core_data_connector/iiif/manifest.rb, app/services/core_data_connector/search/base.rb
This pull request adds the ability to provide a `min_year` or `max_year` parameter to the `/public/core_data/v1/events` API endpoint. It also updates the search service to include a `event_range_facet` attribute for each record.
It also fixes a bug in the IIIF Collection generation, where the `Manifest` items were not correctly being given a `v1` URL as the identifier.
=> CDC #269 - Events Filters

app/controllers/core_data_connector/application_controller.rb, app/controllers/core_data_connector/items_controller.rb, app/controllers/core_data_connector/projects_controller.rb, app/services/core_data_connector/import_analyze/import.rb, app/services/core_data_connector/import_analyze/policy.rb
This pull request fixes a bug in the Import From FairCopy.cloud workflow when trying to import a document as a non-admin user. When a non-admin user initiates the import, there is an authorization check to ensure that the user is only importing records into project(s) for which they have access. We do this authorization check at two different points in the workflow:
1. After loading the CSV files from FairCopy.cloud, prior to presenting the user with the lists of records being imported
2. Before sending the CSV files to the server to be imported into Core Data
In each case, the data is formatted slightly differently, however, the authorization check was assuming the same format. The solution here was to split the checks out into `has_analyze_access?` and `has_import_access?` in the …
=> CDC #277 - Import Error

Gemfile, Gemfile.lock, app/models/core_data_connector/organization.rb, app/models/core_data_connector/person.rb, app/models/core_data_connector/place.rb, app/services/core_data_connector/search/base.rb
This pull request updates the `user_defined_fields` gem to the latest version to make use of the `converter` module to help convert user-defined field string values to the appropriate types.
This pull request also updates the `organization`, `place`, and `person` models to allow `nil` values on delegates to names to avoid exceptions causes by bad data.
=> CDC #212 - Index user defined fields

app/services/core_data_connector/search/base.rb
This pull request removes the `all_projects_facet` and `owner_project_facet` fields and adds the `name_facet` to the nested objects.
=> CDC #291 - Projects facets

Gemfile, Gemfile.lock, app/controllers/core_data_connector/projects_controller.rb, app/services/core_data_connector/export/exporter.rb, app/services/core_data_connector/import/base.rb
This pull request updates the `user_defined_fields` gem to the latest version and adds support to the import/export process for better handling of some user-defined field types.
This pull request also fixes the issue in #236.
=> CDC #116 - Fuzzy Dates

app/services/core_data_connector/search/person.rb
This pull request fixes a bug indexing `people` records into Typesense. The `/search/person.rb` class was using an attribute called `name`, which does not exist on the `person` model. We'll instead use a block to generate the full name for the `person`.
=> CDC #298 - Index error

app/services/core_data_connector/export/base.rb, app/services/core_data_connector/export/exporter.rb, app/services/core_data_connector/import_analyze/import.rb
This pull request fixes an issue with the import from FairCopy.cloud object comparison. For fuzzy date and multi-select user-defined field types, we were not correctly parsing the JSON string values, which lead to a false negative during comparison.
=> CDC #292 - Import Compare

lib/typesense/helper.rb
Per Atlas and performant-software/core-data-cloud#323, allow sorting on the `name` and `name_facet` fields.
- This only applies during collection creation at the schema definition stage, so existing collections will need to be recreated or manually modified.
- Consuming clients will need to specify the sort field and direction in order to take advantage of it.
=> Make 'name' string field sortable during typesense schema creation

app/services/core_data_connector/import_analyze/event.rb, app/services/core_data_connector/import_analyze/import.rb, app/services/core_data_connector/import_analyze/instance.rb, app/services/core_data_connector/import_analyze/item.rb, app/services/core_data_connector/import_analyze/organization.rb, app/services/core_data_connector/import_analyze/person.rb, app/services/core_data_connector/import_analyze/place.rb, app/services/core_data_connector/import_analyze/taxonomy.rb, app/services/core_data_connector/import_analyze/work.rb
This pull request fixes a bug that occurs when importing records from FairCopy.cloud and using the "Remove duplicates" option. We were using simple column names (`name`, `last_name`, etc) in the `GROUP BY` clause of the SQL query that finds the duplicates, which let to the potential for ambiguous column names.
The solution is to use AREL column objects instead, which will ensure that the generated SQL is properly namespaced with the table name prefix.
=> CDC #325 - Import error

app/services/core_data_connector/import_analyze/event.rb, app/services/core_data_connector/import_analyze/instance.rb, app/services/core_data_connector/import_analyze/item.rb, app/services/core_data_connector/import_analyze/organization.rb, app/services/core_data_connector/import_analyze/person.rb, app/services/core_data_connector/import_analyze/place.rb, app/services/core_data_connector/import_analyze/taxonomy.rb, app/services/core_data_connector/import_analyze/work.rb
This pull request fixes a bug that occurs when attempting to use the "Remove duplicates" toggle for "events.csv" or "taxonomies.csv". The group by columns in the `import_analyze` service were not name spaced, and as a result, were throwing an error for models with the same name as the module. For consistency, all columns have been prefixed with the `CoreDataConnector` module.
=> CDC #330 - Remove duplicates

app/services/core_data_connector/export/base.rb, app/services/core_data_connector/import/base.rb, app/services/core_data_connector/import/events.rb, app/services/core_data_connector/import/instances.rb, app/services/core_data_connector/import/items.rb, app/services/core_data_connector/import/organizations.rb, app/services/core_data_connector/import/people.rb, app/services/core_data_connector/import/places.rb, app/services/core_data_connector/import/relationships.rb, app/services/core_data_connector/import/taxonomies.rb, app/services/core_data_connector/import/works.rb
This pull request fixes a bug that occurs during the import process when all user-defined fields are not included in the CSVs. The import process will overwrite existing values that are not included as columns, resulting in lost data.
The solution here was to update existing records during the `transform` phase with any `user_defined` values, and union the existing values with the incoming values from the CSV files using the `||` operator.
=> CDC #321 - Import UDFs

lib/typesense/helper.rb
This PR improves Typesense index performance and API payloads by setting the `index` attribute to `false` for the `geometry` object when places are indexed.
The `index` attribute being disabled prevents Typesense from doing any processing on the value (e.g. tokenization, etc.), but keeps it on the disk and in search API responses. This optimization is particularly relevant for polygon data, as `geometry` can be 1 MB or more in those cases.
=> Set `index` to `false` for `geometry` object in typesense

app/services/core_data_connector/import_analyze/import.rb, app/services/core_data_connector/merge/merger.rb
This pull request fixes two issues with the `import_analyze` and `merge` services:
The `import_analyze` service was not including records that had been merged by a previous import if they were not contained within the current import. The solution here was to add an additional row for the existing record (complete with merged UUIDs) which will then correctly appear as a merged record.
The `merge` service was using `=` to set new related records, which was immediately saving to the database. This caused callbacks to be executed, which was erroneously deleting records. We've updated the service to use `build` instead, which will _not_ make calls directly to the database, but wait for us to save the parent record.
=> CDC #353 - Import duplicates

app/services/core_data_connector/import/base.rb, app/services/core_data_connector/import/events.rb, app/services/core_data_connector/import/instances.rb, app/services/core_data_connector/import/items.rb, app/services/core_data_connector/import/organizations.rb, app/services/core_data_connector/import/people.rb, app/services/core_data_connector/import/places.rb, app/services/core_data_connector/import/taxonomies.rb, app/services/core_data_connector/import/works.rb, app/services/core_data_connector/import_analyze/import.rb
This pull request fixes two separate issues that were occurring when importing records that contain user-defined fields:
1. When a record had previously been imported and merged with another record, the import would result in an exception due to a mismatch in the number of columns after analyzing the CSV files. The row returned from the server would not contain columns for user-defined fields with `nil` values, while existing and new records would. If the first record in the CSV happened to be imported previously and merged, the import would fail. The solution here was to update the `record_to_csv` method to add those empty user-defined field values to the resulting object.
2. Importing of user-defined field values would result in the `user_defined` column not being updated if the …
=> CDC #371 - Import user defined fields

app/controllers/concerns/core_data_connector/public/v1/nestable_controller.rb, config/routes/public/v1.rb
This pull request adds the missing `/public/v1/organizations` API endpoint. Since the controllers exist, I believe this route was omitted in error.
=> CDC #358 - Organizations API endpoint

app/controllers/concerns/core_data_connector/public/v1/nestable_controller.rb, app/models/core_data_connector/relationship.rb, app/services/core_data_connector/search/base.rb, app/services/core_data_connector/search/place.rb, config/routes/public/v1.rb, lib/typesense/helper.rb
This pull request updates the search module to include the `coordinates` field for related place records. In order to accomplish this, we defined a couple new relationships in `relationship.rb` for the `relationship` -> `place` record that uses a scope to include the centroid for the related place.
This pull request also updates the `update` call to Typesense to convert any field with "coordinates" in the name from a `float[]` to `geopoint[]`.
**Note:** This pull request also includes the changes in [#358](https://github.com/performant-software/core-data-cloud/issues/358).
=> CDC #357 - Related place coordinates

app/serializers/core_data_connector/public/v1/user_defined_serializer.rb
This pull request adds the `type` attribute to the `UserDefinedSerializer`. This will allow consumers to determine how to handle the field value.
=> CDC #375 - User-defined type

app/policies/core_data_connector/project_policy.rb, app/serializers/core_data_connector/projects_serializer.rb, db/migrate/20250204210235_add_map_library_url_to_core_data_connector_projects.rb
Per performant-software/core-data-cloud#380:
- For `Project`, add `map_library_url` as create/update attribute, index/show serializer attribute
=> Add map_library_url to project permitted attributes, serializer (CDC #380)

app/controllers/core_data_connector/projects_controller.rb, app/policies/core_data_connector/project_policy.rb, app/services/core_data_connector/map_library.rb, config/routes/admin.rb
Per https://github.com/performant-software/core-data-cloud/pull/383#discussion_r1951595693:
- Add `/project/:id/map_library` endpoint, which sends a GET request to the project's map library URL and returns the result
=> Add map library fetch and endpoint (CDC #380)

app/models/core_data_connector/event.rb, app/models/core_data_connector/instance.rb, app/models/core_data_connector/item.rb, app/models/core_data_connector/work.rb
Per #133:
- Implement `resolve_definable` for Events so that UDF validation will only apply to Events of the same project model.
Also:
- Update argument names for other `resolve_defineable` implementations to match the `Fieldable` classes' class names.
=> Fix user-defined field validation for Events (#133)

Gemfile.lock, app/models/core_data_connector/taxonomy.rb, app/policies/core_data_connector/taxonomy_policy.rb, app/serializers/core_data_connector/taxonomies_serializer.rb, app/services/core_data_connector/import/taxonomies.rb, db/migrate/20250226175155_add_user_defined_fields_to_core_data_connector_taxonomies.rb
Per performant-software/core-data-cloud#398:
- Add column and index for `user_defined` `jsonb` field to `core_data_connector_taxonomies`
- Update `Taxonomy` model, serializer, policy, and import processor to handle UDFs
=> Add user-defined fields to Taxonomy (CDC #398)

app/controllers/concerns/core_data_connector/public/v1/nestable_controller.rb, config/routes/public/v1.rb
An attempt to add a `/public/v1/media_contents` endpoint that takes a `project_ids` parameter. See https://github.com/performant-software/core-data-cloud/issues/401
I am modeling this off of the recent addition of the `/organizations` endpoint, and as best I can tell from poking around the code this should work the same way; but I'm not super familiar with the code and am not currently set up to test locally, so I might have missed something.
=> Adding `media_contents` endpoint

app/services/core_data_connector/search/event.rb, config/initializers/time_formats.rb
My initial attempt to convert the `start_date` and `end_date` fields for `events` to integer years when indexing in Typesense.
=> Indexing start and end years instead of timestamps

app/services/core_data_connector/search/base.rb, app/services/core_data_connector/search/place.rb
This PR adds back the `search_query` method (and the call to it that occurred in `Search::Base` that was accidentally removed in https://github.com/performant-software/core-data-connector/pull/122.
It might be possible to refactor this so `search_query` is only called on Places instead of running the `if self.respond_to?(:search_query)` check on all models, but I guess we can't add a `for_search` to `Search::Place` that adds the coordinates and then calls `super` because `Search::Place` isn't actually a subclass of `Search::Base`?
=> Fix missing `coordinates` field by adding `search_query` method back to `Search::Place`

app/controllers/core_data_connector/public/v1/public_controller.rb, app/controllers/core_data_connector/relationships_controller.rb, app/policies/core_data_connector/relationship_policy.rb, app/serializers/core_data_connector/relationships_serializer.rb, db/migrate/20250407150531_add_order_to_relationships.rb
- adds a new optional integer `order` field to the `core_data_connector_relationships` table
- updates `RelationshipsController` and `Public::V1::PublicController` to sort related records by `order`
=> `order` field for relationships

app/models/core_data_connector/media_content.rb
This PR updates the `MediaContent` model to call the `reset_manifests_by_type` method of `Iiif::Manifest` when a media content record is updated to regenerate the associated manifest.
In other words, when you update a user-defined field on an image, any manifests containing that image will be updated to contain the new UDF value.
=> Update relationship manifests when a `MediaContent` record's UDFs are updated

app/controllers/concerns/core_data_connector/public/v1/nestable_controller.rb, app/controllers/core_data_connector/public/v0/public_controller.rb, app/controllers/core_data_connector/public/v1/public_controller.rb
This pull request fixes an issue with the nested routes in the public API. The problem was that requests for related records for a record that doesn't exist (e.g. `GET /places/abcdefg/events`) will return all records in the project.
The solution was to remove the `current_record.present?` check from the `nested_resource?` method. This way we can take separate action if the request is for a nested resource and the base record does not exist.
=> CDC #438 - Nested routes

app/models/core_data_connector/media_content.rb, app/models/core_data_connector/project.rb, db/migrate/20250724125222_add_uuid_to_projects.rb, db/migrate/20250724125258_add_use_storage_key_to_projects.rb, db/migrate/20250724135202_update_projects_use_storage_key_default.rb
This pull request adds the `uuid` and `use_storage_key` columns to the `projects` table. The idea here is that we'll generate a unique identifier for each project created and store all of the media associated with that project in S3 under a folder identified by the `uuid` value.
The reason we're initially setting the `use_storage_key` value to "false" then flipping it to "true" is so that existing projects can continue to _not_ use a storage key and we won't be required to rename any existing objects, but new projects will have their objects separated into folders.
@jamiefolsom - Any thoughts on whether we need to migrate the S3 objects for existing projects into folders?
=> CDC #470 - Storage keys

app/controllers/core_data_connector/items_controller.rb, app/controllers/core_data_connector/jobs_controller.rb, app/controllers/core_data_connector/projects_controller.rb, app/jobs/core_data_connector/import_csv_job.rb, app/models/core_data_connector/job.rb, app/policies/core_data_connector/job_policy.rb, app/policies/core_data_connector/user_policy.rb, app/serializers/core_data_connector/jobs_serializer.rb, app/services/core_data_connector/import/events.rb, app/services/core_data_connector/import_analyze/helper.rb, app/services/core_data_connector/import_analyze/import.rb, app/services/core_data_connector/import_analyze/policy.rb, config/routes/admin.rb, db/migrate/20250725104315_create_core_data_connector_jobs.rb
This pull request makes the following changes to support running imports as background jobs:
- Creates the `core_data_connector_jobs` table
- Adds the `GET /core_data/jobs` API endpoint
- Refactors the import helpers to create `Job` records
- Adds the `ImportCsvJob` ActiveJob class
- Fixes a bug with the `FuzzyDate::accuracies` enum
=> CDC #474 - Import jobs
